### ISSUE TITLE
[Feature Request] Add additional sensors from the API

### ISSUE THREAD

**Issue by Scoop2389** [jaydeethree/Home-Assistant-weatherdotcom#15]
I am requesting a few sensors be added to this integration that are part of the weather.com API:
**Current Condition**
pressureTendencyTrend: Pressure Tendency
cloudCeiling: Cloud Ceiling
**Forecast**
narrative: I suggest this be implemented similar to the official AccuWeather entity in which there are sensors named "Weather Description 0d day" "Weather Description 0d night" "Weather Description 1d day" and so on.
thunderCategory: Chance of Thunderstorms, could be enumerated like Weather Description

**Comment by jaydeethree** [comment]
Thanks for making sure this data exists in the API, that makes things easier :)

The current condition sensors should be very easy to add. The forecast sensors are a bit more complicated because right now this integration only exposes forecast data that's natively supported by Home Assistant:

https://developers.home-assistant.io/docs/core/entity/weather/#forecast-data

Creating additional sensors for forecast data is definitely possible, but since it's something that this integration isn't doing yet it will require a bit more work. I'm not sure if I feel like this is valuable enough to add, but if enough people want this then I can add it.

I should have time to add the current condition sensors later this week.

**Comment by Scoop2389** [comment]
Yeah, that makes sense. The weather description forecast would be pretty useful for me, the thunder category isn't something that I need but would be nice to have.

**Comment by jaydeethree** [comment]
The current condition sensors have been added in https://github.com/jaydeethree/Home-Assistant-weatherdotcom/commit/893fc4ae565ba53d09c884498aac2f776aeabbdd, which is now available as version 1.1.1.

For the additional forecast sensors I unfortunately don't have time to add them as things are quite busy in my personal life right now. If someone else wants to send a PR to add them then I'd be happy to review it though :)
