### ISSUE TITLE
some weather descriptions are too long

### ISSUE THREAD

**Issue by tonyis49** [jaydeethree/Home-Assistant-weatherdotcom#29]
Hi,
this is more of a suggestion than an issue in that some of the weather descriptions are quite long.
e.g. "Showers in the Vicinity" could be "Local Showers"

**Comment by jaydeethree** [comment]
The descriptions come from the Weather.com API, specifically the `wxPhraseLong` property. The API also provides shorter descriptions in the `wxPhraseMedium` and `wxPhraseShort` properties, but those two properties are only available when the configured language is US English. It's important to me that this integration supports other languages and is not English-specific, so that's why I decided to use the `wxPhraseLong` property for weather descriptions.

For reference, the API docs can be found here:

https://docs.google.com/document/d/1UOjfN1j54Ocmwj-zYCcHG_RM1tlNceW_qlzz0wVILXA/edit
