### ISSUE TITLE
Implement AirQuality

### ISSUE THREAD

**Issue by GoNzCiD** [jaydeethree/Home-Assistant-weatherdotcom#30]
It should be possible to implement air quality sensors within this documentation? (not tested)
https://docs.google.com/document/d/1rcYHmIaGKtiINuEPJXGMWU5OEntPf2i0U8BBO8clmtQ/edit

**Comment by jaydeethree** [comment]
That's a different API endpoint than this integration uses, so it would require an additional call to the API. While it's certainly possible to add another API call, I'm intentionally trying to limit the API calls because this is not supposed to be a publicly-accessible API.

Air quality data is already available in Home Assistant through several other integrations, so I would recommend using one of those to get this data:

https://www.home-assistant.io/integrations/#health
